# permissions for end users to edit mandates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: prokura
    app.kubernetes.io/managed-by: kustomize
  name: mandate-editor-role
rules:
- apiGroups:
  - prokura.dev
  resources:
  - mandates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - prokura.dev
  resources:
  - mandates/status
  verbs:
  - get
